### PR TITLE
Enable sending more than 60 000 characters with crash on Description

### PR DESCRIPTION
**Pull request by tapanila**

### CODE REVIEW

**Comment by lumaxis** [comment]
Thanks for the contribution @tapanila! We'll take a look at this and get back to you :relaxed:

**Comment by tapanila** [comment]
1. Documentation says that but the real limit is 65520. I think the MSDN documentation should be updated

2. Will add that

**Comment by mihailsm** [comment]
I am not comfortable to go against MSDN documentation now. Let's update to MSDN documentation limit or wait until MSDN will officially declare another limit.

**Comment by tapanila** [comment]
Updated the limit to be according to MSDN documentation.

Would you happen to know who to contact to get MSDN documentation corrected?

**Comment by mihailsm** [comment]
The best way - to use "Any suggestions?" link on the MSDN page.

**Pull request merged**
