### PR TITLE
Update min version of UWP to prevent compression problems

### PR DESCRIPTION
**Pull request by MatkovIvan**
UWP version 5.2.0 contains [a known issue](https://social.msdn.microsoft.com/Forums/en-US/e766a904-7346-4f76-bad2-852d3b301b0e/known-issue-version-52-of-microsoftnetcoreuniversalwindowsplatform-delisted-all?forum=Win10SDKToolsIssues) with missing `clrcompression.dll`.
HockeySDK relies on functionality above so people can see the SDK crash when UWP version 5.2.0 is used: [example report](https://support.hockeyapp.net/discussions/problems/68180-systemiocompression-crash-on-arm-when-hockeyapp-is-used).
This PR bumps min UWP version required to prevent this issue.

PR also removes auto generated `.lock.json` files from the repo.

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by ArefGihuni** [comment]
hi @MatkovIvan 
I built it using version 5.2.2 and also 5.3.3 which is available now. But still app crashes after resuming with this error:
The underlying compression routine could not be loaded correctly.
...
Unable to load DLL 'clrcompression.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by MatkovIvan** [comment]
@ArefGihuni What is "it"? Please provide more info to reproduce the issue. Ideally - sample app :)

**Comment by ArefGihuni** [comment]
@MatkovIvan it is this SDK. 

I actually tried to reproduce it, in my real project the above error occurs, but in a new project, it doesn't!
In my real project I removed HockeyApp sdk and code, and the crash doesn't happen. So it definitely is caused by HockeyApp.

**This is what I did (using VS2017):**
- Downloaded zip file of this SDK
- Updated NuGet package of  _Microsoft.NETCore.UniversalWindowsPlatform_ to version 5.3.3
- Got rid of _HockeySDK.WINRT.NuGet_ and _HockeySDK.WP.NuGet_ because they caused an error when I tried to build and I'm only interested in UWP.
- Built it in release mode.

**Then in my project**
- Min version Build 10240, target version Build 14393
- Updated NuGet package of  _Microsoft.NETCore.UniversalWindowsPlatform_ to version 5.3.3 also.
- Added a reference to _Microsoft.HockeyApp.Core45.dll_ and _Microsoft.HockeyApp.Kit.dll_ that are in this folder

> bin\Release\Kit.UWP

- Built, and this error appeared: 

> Payload file 'bin\Release\Kit.UWP\Microsoft.HockeyApp.Kit\Properties\Microsoft.HockeyApp.Kit.rd.xml' does not exist

But there was a file in this path, so I copied this there. ( Am I doing wrong?)

> bin\Release\Kit.UWP\Microsoft.HockeyApp.Kit\Properties\Microsoft.HockeyApp.Kit.rd.xml

finally to configure HockeyApp, added the following code in constructor of _App.xaml.cs_
HockeyClient.Current.Configure("appId");

Now when deploy it to mobile, open the app, lock the screen. after a moment when unlock the phone again, app crashes, with the error message I described previously.

**Comment by ArefGihuni** [comment]
Is it possible to download the SDK with your commit included? sorry I'm not much familiar with git and github

**Comment by ArefGihuni** [comment]
it is this SDK. 
I need to look more into it. Strangely app crashes when I use the SDK in my real project, but not in a new app.

**Comment by MatkovIvan** [comment]
@ArefGihuni Also, please look at [answer](https://support.hockeyapp.net/discussions/problems/68180-systemiocompression-crash-on-arm-when-hockeyapp-is-used) related to sqlite

**Pull request merged**
