### PR TITLE
Implemented core functionality for WPF

### PR DESCRIPTION
**Pull request by edoust**
This pull request contains a stable implementation of the HockeySDK features for WPF:

- Crash reports (including method metadata tokens, IL offsets, assembly signature and age values - in combination, a lookup of the original source code lines is possible)
- Session telemetry
- Custom Events

The other telemetry works too (e.g. page views, exceptions, etc.) but I did not thoroughly test that

**Attachments**
[Sample CrashReport](https://github.com/bitstadium/HockeySDK-Windows/files/619023/CrashReport.txt)

### CODE REVIEW

**Comment by izikl** [comment]
@edoust thank you for your contribution, it looks good to me. One minor comment inline. 
About testing:
On which OSs have you tested this code?

**Comment by edoust** [comment]
@izikl thanks for the feedback. I tested the code on Windows 7 and Windows 8.1 (inside a virtual machine). All areas of the crash reports are filled with the correct information

**Comment by darvell** [comment]
Any timeline on this being pulled in followed by a new build on nuget? Radio silence for nearly a month is a bit scary...

**Comment by izikl** [comment]
@darvell Our team is on vacation for the holidays, but we plan to do it after the new year. 

Happy new year 🎆

**Comment by dougnutz** [comment]
@darvell Sorry for the long delay we are planning to address this by the end of the week.

**Comment by dougnutz** [comment]
We have move this request in to a community branch https://github.com/bitstadium/HockeySDK-Windows/tree/community .
We will also be updating the docs appropriately. But in general new work will be going into the community branch, hi priority bug fixes and security issues will be addressed in the master branch.  Our goal is to focus on Mobile center sdks (https://mobile.azure.com/) as the future of HockeySDK.

**Comment by andershol** [comment]
@dougnutz I can't see that benefit come from using two branches. It seems that this will only make i more cumbersome to work with.
Are you creating the nuget packages from the "community" branch? Otherwise it just seem like a backhanded way of rejecting the patch.
You focusing on the mobile center, shouldn't really affect which branch you accept patches into.
Anyway, I hope that you release a new nuget package with this badly needed functionality soon.

**Comment by aelij** [comment]
Hi, do you have an estimate when will this PR be merged and published to NuGet? This functionality is really missing.

The telemetry API doesn't work at all right now. I've spent quite a few hours trying to figure out why I'm not receiving any events.

**Comment by codekaizen** [comment]
What is the status of this PR? It looks like it has been approved for quite some time - why is it not merged in and released?

**Comment by glen-nicol** [comment]
Any way we can get this through? Session telemetry seems like core functionality that is sorely missed on WPF.

**Comment by darvell** [comment]
I guess this PR has been abandoned like WPF. There's the community branch I guess but no way to get a nuget package from it. What a let down, WPF is still important since not everyone can build their products in a sandboxed environment, as well as a lot of us still have to target Vista/7 and this feature would be so handy.

**Comment by elamalani** [comment]
Hi everyone, 

I'd like to share what our product team is working on and why are we a little hesitant to merge this PR. We don't want to abandon HockeyApp community at all, but our focus is shifted to work on this new product from Microsoft - [App Center ](appcenter.ms) which is the next generation of HockeyApp. You can learn more about Visual Studio App Center on the [HockeyApp ](https://www.hockeyapp.net/appcenter/about/) website as well. 

Given that we are heads down working on App Center since over a year and a half, we want all the new platforms and functionalities to be added in App Center, which has [open source SDK](https://github.com/search?q=org%3AMicrosoft+appcenter) just like HockeyApp. WPF is a new platform that HockeyApp doesn't support at the moment, so it's in our backlog to support it in **App Center** rather than HockeyApp as we know there is a large developer community targeting WPF apps. For HockeySDK, we instead created a community branch so that you all can contribute and work easily on that branch rather than waiting on us.

I hope you understand our rationale behind this. Please let me know if you have any questions and I'd be happy to answer them.

Thanks,
Ela

**Pull request closed without merging**
